language: node_js
node_js: 
   - "node"

before_script:
  - npm install

script: 
  - npm run build

cache:
  directories:
    - "node_modules"

before_deploy:
  - cd dist

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master